## dogecoin.persistentvolumeclaim.yml
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: "dogecoin"
  name: "dogecoin-core"
spec:
  storageClassName: slow
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 150Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "dogecoin-core"
  labels:
    type: "local"
spec:
  storageClassName: "slow"
  capacity:
    storage: "150Gi"
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/ssd/dogecoin"
---
